config/routes.rb
Rails.application.routes.draw do
  resources :workouts
  resources :exercise_sets
  resources :exercises
  resources :routines
  resources :routine_sets

   root 'exercises#index'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  has_many :exercise_sets
  has_many :routines, :through =>  :routine_sets

end

app/models/exercise_set.rb
class ExerciseSet < ActiveRecord::Base
  belongs_to :exercise
  belongs_to :workout
end

app/models/routine.rb
class Routine < ActiveRecord::Base
  has_many :routine_sets
  has_many :exercises, :through => :routine_sets

  accepts_nested_attributes_for :routine_sets
end

app/models/routine_set.rb
class RoutineSet < ActiveRecord::Base
  belongs_to :exercise
  belongs_to :routine

  accepts_nested_attributes_for :routine
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :exercise_sets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercise_sets_controller.rb
class ExerciseSetsController < ApplicationController
  before_action :set_exercise_set, only: [:show, :edit, :update, :destroy]

  # GET /exercise_sets
  # GET /exercise_sets.json
  def index
    @exercise_sets = ExerciseSet.all
  end

  # GET /exercise_sets/1
  # GET /exercise_sets/1.json
  def show
  end

  # GET /exercise_sets/new
  def new
    @exercise_set = ExerciseSet.new
  end

  # GET /exercise_sets/1/edit
  def edit
  end

  # POST /exercise_sets
  # POST /exercise_sets.json
  def create
    @exercise_set = ExerciseSet.new(exercise_set_params)

    respond_to do |format|
      if @exercise_set.save
        format.html { redirect_to @exercise_set, notice: 'Exercise set was successfully created.' }
        format.json { render :show, status: :created, location: @exercise_set }
      else
        format.html { render :new }
        format.json { render json: @exercise_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercise_sets/1
  # PATCH/PUT /exercise_sets/1.json
  def update
    respond_to do |format|
      if @exercise_set.update(exercise_set_params)
        format.html { redirect_to @exercise_set, notice: 'Exercise set was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise_set }
      else
        format.html { render :edit }
        format.json { render json: @exercise_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercise_sets/1
  # DELETE /exercise_sets/1.json
  def destroy
    @exercise_set.destroy
    respond_to do |format|
      format.html { redirect_to exercise_sets_url, notice: 'Exercise set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise_set
      @exercise_set = ExerciseSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_set_params
      params.require(:exercise_set).permit(:weight_kg, :repetition)
    end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:name, :main_muscles, :bodypart, :force, :mechanics_type)
    end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :set_routine, only: [:show, :edit, :update, :destroy]
  before_action :set_exercises, only: [:new, :edit]

  def index
    @routines = Routine.all
  end

  def show
  end

  def new
    @routine = Routine.new
    @routine.routine_sets.build
  end

  def create
    @routine = Routine.new(routine_params)
    # @routine_set = RoutineSet.new(routine_set_params)

    respond_to do |format|
      if @routine.save
        format.html { redirect_to @routine, notice: 'Routine was successfully created.' }
        format.json { render :show, status: :created, location: @routine }
      else
        format.html { render :new }
        format.json { render json: @routine.errors, status: :unprocessable_entity }
      end
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def routine_params
    params.require(:routine).permit(:name, routine_sets_attributes: [:exercise_id, :routine_id, :sets, :repetition,
                                                                     :rest_time])
  end

  def set_routine
  @routine = Routine.find(params[:id])
  end

  def set_exercises
    @exercises = Exercise.all
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:date, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercise_sets_helper.rb
module ExerciseSetsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercise_sets/_form.html.erb
<%= form_for(@exercise_set) do |f| %>
  <% if @exercise_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise_set.errors.count, "error") %> prohibited this exercise_set from being saved:</h2>

      <ul>
      <% @exercise_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight_kg %><br>
    <%= f.number_field :weight_kg %>
  </div>
  <div class="field">
    <%= f.label :repetition %><br>
    <%= f.number_field :repetition %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercise_sets/edit.html.erb
<h1>Editing Exercise Set</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise_set %> |
<%= link_to 'Back', exercise_sets_path %>

app/views/exercise_sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exercise Sets</h1>

<table>
  <thead>
    <tr>
      <th>Weight kg</th>
      <th>Repetition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercise_sets.each do |exercise_set| %>
      <tr>
        <td><%= exercise_set.weight_kg %></td>
        <td><%= exercise_set.repetition %></td>
        <td><%= link_to 'Show', exercise_set %></td>
        <td><%= link_to 'Edit', edit_exercise_set_path(exercise_set) %></td>
        <td><%= link_to 'Destroy', exercise_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise set', new_exercise_set_path %>

app/views/exercise_sets/new.html.erb
<h1>New Exercise Set</h1>

<%= render 'form' %>

<%= link_to 'Back', exercise_sets_path %>

app/views/exercise_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight kg:</strong>
  <%= @exercise_set.weight_kg %>
</p>

<p>
  <strong>Repetition:</strong>
  <%= @exercise_set.repetition %>
</p>

<%= link_to 'Edit', edit_exercise_set_path(@exercise_set) %> |
<%= link_to 'Back', exercise_sets_path %>

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :main_muscles %><br>
    <%= f.text_field :main_muscles %>
  </div>
  <div class="field">
    <%= f.label :bodypart %><br>
    <%= f.text_field :bodypart %>
  </div>
  <div class="field">
    <%= f.label :force %><br>
    <%= f.text_field :force %>
  </div>
  <div class="field">
    <%= f.label :mechanics_type %><br>
    <%= f.text_field :mechanics_type %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Exercise', new_exercise_path, class: 'btn btn-primary' %>

<h1>Listing Exercises</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Main muscles</th>
      <th>Bodypart</th>
      <th>Force</th>
      <th>Mechanics type</th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= link_to exercise.name, exercise %></td>
        <td><%= exercise.main_muscles %></td>
        <td><%= exercise.bodypart %></td>
        <td><%= exercise.force %></td>
        <td><%= exercise.mechanics_type %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path, class: 'btn btn-default' %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exercise.name %>
</p>

<p>
  <strong>Main muscles:</strong>
  <%= @exercise.main_muscles %>
</p>

<p>
  <strong>Bodypart:</strong>
  <%= @exercise.bodypart %>
</p>

<p>
  <strong>Force:</strong>
  <%= @exercise.force %>
</p>

<p>
  <strong>Mechanics type:</strong>
  <%= @exercise.mechanics_type %>
</p>

<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Exercises', exercises_path, class: 'navbar-brand' %>
      <%= link_to 'Routines', routines_path, class: 'navbar-brand' %>
      <%= link_to 'My Workouts', workouts_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gym Log" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Gym Log" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/routines/_form.html.erb
<%= form_for(@routine) do |f| %>
    <% if @routine.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@routine.errors.count, "error") %> prohibited this routine from being saved:</h2>

          <ul>
            <% @routine.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>



      <div class="form-group">
        <%= f.fields_for :routine_sets do |set| %>
            <%= set.label :exercise_id, "Exercises" %>
            <%= set.select :exercise_id, options_from_collection_for_select(@exercises, :id, :name), {:multiple => true} %>

            <%= set.label :sets, "Number of sets" %>
            <%= set.text_field :sets %>

            <%= set.label :repetition, "Reps" %>
            <%= set.text_field :repetition %>

            <%= set.label :rest_time, "Rest time" %>
            <%= set.text_field :rest_time %>

            <%= set.hidden_field :routine_id %>
        <% end %>
      </div>

    </div>

    <div class="actions">
      <%= f.submit class: 'btn btn-success' %>
    </div>
<% end %>

app/views/routines/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Routine', new_routine_path, class: 'btn btn-primary' %>

<h1>Routines</h1>

<table class="table table-bordered">
  <thead>
  <tr>
    <th class="col-xs-1">Name</th>
  </tr>
  </thead>

  <tbody>
  <% @routines.each do |routine| %>
      <% if routine.name %>
          <tr>
            <td><%= link_to routine.name, routine %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/routines/new.html.erb
<h1>New Routine</h1>

<%= render 'form' %>

<%= link_to 'Back', routines_path, class: 'btn btn-default' %>

app/views/routines/show.html.erb
<p id="notice"><%= notice %></p>
<h3><%= @routine.name %></h3>
<table class="table table-bordered">
  <thead>
  <th>Exercise name</th>
  <th>Sets</th>
  <th>Reps</th>
  <th>Rest time</th>
  </thead>
  <tbody>
  <% @routine.routine_sets.each do |set| %>
      <tr>
        <td><%= link_to set.exercise.name, set.exercise %></td>
        <td><%= set.sets %></td>
        <td><%= set.repetition %></td>
        <td><%= set.rest_time %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back to Routines', routines_path %>

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Workout', new_workout_path, class: 'btn btn-primary' %>

<h1>My Workouts</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Date</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= link_to workout.date.to_date, workout %></td>
        <td><%= workout.notes %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path, class: 'btn btn-default' %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<h4>Date: <%= @workout.date.to_date %></h4>

<h4>Notes</h4>
<p><%= @workout.notes %></p>

<table class="table table-bordered">
  <thead>
  <th class="col-md-1">Exercise</th>
  <th class="col-md-1">Weight (kg)</th>
  <th class="col-md-1">Repetition</th>
  </thead>
  <tbody>
  <% @workout.exercise_sets.each do |set| %>
      <tr>
        <td><%= link_to set.exercise.name, set.exercise %></td>
        <td><%= set.weight_kg %></td>
        <td><%= set.repetition %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Destroy', @workout, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Edit', edit_workout_path(@workout) %>